public enum EffectType
{
    Buff,
    Regeneration,
    Vampirism,
    DoubleShot,
    DoubleBlow,
    Debuff,
    DamageOverTime,
    Stun,
    Root,
    Madness,
    Petrify,
    Forgetfulness,
    Hypnosis,
    Bloodlust,
    AreaStrike,
    PiercingStrike,
    UnansweredStrike,
    ExplosiveShot,
    ExplosiveShotLiving
}